sonar.projectKey=sumanthvartha_sonar-demo
sonar.organization=sumanthvartha
sonar.projectName=sonar-demo
sonar.sources=.
sonar.language=py
sonar.python.coverage.reportPaths=coverage.xml
sonar.exclusions=**/__pycache__/**